name:  Test
on:
  workflow_dispatch:

jobs:
  turnstyle:
    runs-on: ubuntu-latest
    steps:
    
       - name: Tests
         uses: DFE-Digital/github-actions/SendToLogit@logit
         with:
           LOGIT_API_KEY: ${{secrets.LOGIT_API_KEY}}
