name: Login Test
on:
  workflow_dispatch:

jobs:
  turnstyle:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    
      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
