name:  Test
on:
  workflow_dispatch:

jobs:
  LOGIT:
    runs-on: ubuntu-latest
    steps:
    
       - name: Tests
         uses: DFE-Digital/github-actions/SendToLogit@logit
         with:
           LOGIT-API-KEY: ${{secrets.LOGIT_API_KEY}}
           logtype: "github"
           JSON: |
                '{"Application":"Get-into-Teaching-Cheese", 
                  "Status":"Success",                       
                  "Action":"Deploy",                        
                  "Environment": "Production",              
                  "Version": "2" }'
