name: Pull Request Test

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:        
    
    - name: Copy PR Info to Release
      run: echo ${{ github.actor }}
            


      
