name: Pull Request Test

on:
  pull_request:
    types: [ opened , synchronize ]
  push:
    branches:
      - master
  
jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Pull Request url
        id: pr-url
        run: |
          echo ::set-output name=url::${$DATA.pull_request.html_url}
        env:
          DATA: ${{ toJson(GITHUB_EVENT_PATH) }}
      
