name: Pull Request Test

on:
  pull_request:
    types: [ opened , synchronize , edited ]

  
jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run:  echo ${github.event}

      
