name: Pull Request Test

on:
  pull_request:
    types: [ opened , synchronize , edited ]

  
jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:        

      - name: Add Trello Comment
        uses: DFE-Digital/github-actions/AddTrelloComment@master
        with:
          MESSAGE:      ${{ github.event.pull_request.html_url }} 
          CARD:         ${{ github.event.pull_request.body }}           
          TRELLO-KEY:   ${{ secrets.TRELLO_KEY}}
          TRELLO-TOKEN: ${{ secrets.TRELLO_TOKEN }}
            


      
