name: Pull Request Test

on:
  workflow_dispatch:

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:        
    
    - name: Copy PR Info to Release
      uses: DFE-Digital/github-actions/CopyPRtoRelease@restrict_to_title
      with:
          PR_NUMBER:  14
          RELEASE_ID: xxxxx
          TOKEN: ${{secrets.GITHUB_TOKEN}}   

            


      
