name: Pull Request Test

on:
  pull_request:
    types: [ opened , synchronize ]
  push:
    branches:
      - master
  
jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
