name: Pull Request Test

on:
  pull_request:
    types: [ opened , synchronize ]
  push:
    branches:
      - master
  
jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:     
      - name: Trigger Review Deployment
        run: |
             echo ${{github.event.number}}
             echo ${{github.event.type}}
             echo $${github.event.message }}
