name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@main
       
     - name: Generate Tag from PR Number
       id:   tag_version
       uses: DFE-Digital/github-actions/GenerateReleaseFromSHA/action.yml@master
       with:
         sha: ${{github.sha}}
               
