name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
     - name: Generate Tag from PR Number
       id:   tag_version
       uses: DFE-Digital/github-actions/GenerateReleaseFromSHA/action.yml@GetIntoTeaching/PR-INFO
       with:
         sha: ${{github.sha}}
               
