name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Validate Key Vault Secrets
          uses: DFE-Digital/github-actions/validate-key-vault-secrets@master
          with:
            KEY_VAULT: ${{ secrets.KEY_VAULT }}
            SECRETS: TTA-KEY
          
          
