name: Run Test Action

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         run: |
             FILE='.github/common_environment.yml'
             while read -r line
             do
                 VAR=$(echo ${line} | sed -e 's/:[^:\/\/]/="/g;s/$/"/g;s/ *=/=/g;s/" */"/g')
                 echo ${VAR} >> $GITHUB_ENV
             done < ${FILE}
             
             
                    
       - name: Print
         run:  |
               echo URL                  = ${{env.SLACK_ICON}}
               echo APPLICATION          = ${{env.APPLICATION}}     
               echo DOCKERHUB_REPOSITORY = ${{env.DOCKERHUB_REPOSITORY}}
               echo DOMAIN               = ${{env.DOMAIN}}
               echo PAAS_APPLICATION_NAME= ${{env.PAAS_APPLICATION_NAME}}
               echo SLACK_FAILURE        = ${{env.SLACK_FAILURE}}
               echo SLACK_SUCCESS        = ${{env.SLACK_SUCCESS}}    
               


