name: Update Release

on:
  workflow_dispatch:

env:
  PR_NUMBER: 10
  RELEASE_ID: 35157528
      
jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: Copy PR to Release
         run: |
              BODY=$(curl -s -X GET "https://api.github.com/repos/${{github.repository}}/pulls/${{env.PR_NUMBER}}" | jq -r ".body" )
              curl -X PATCH -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository}}/releases/${{env.RELEASE_ID}} -d '{"body":"$BODY"}'
               


