name: Update Trello

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
        - name: Update Trello
          uses: DFE-Digital/github-actions/AddTrelloComment@Get_into_teaching/Update-trello
          with:
            MESSAGE:      "HELLO"
            CARD:         https://trello.com/c/gFLtDH7X/1-eg-book-flights            
            TRELLO-KEY:   ${{ secrets.TRELLO_KEY}}
            TRELLO-TOKEN: ${{ secrets.TRELLO_TOKEN }}
          
          
