name: Update Trello

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
        - name: Update Trello
          uses: DFE-Digital/github-actions/UpdateTrello@Get_into_teaching/Update-trello
          with:
            TRELLO-KEY:   ${{ secrets.TRELLO-KEY}}
            TRELLO-TOKEN: ${{ secrets.TRELLO-TOKEN }}
          
          
