name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
       
     - name: Get Release Id from Tag
       id: tag_id
       uses: DFE-Digital/github-actions/DraftReleaseByTag@master
       with:
         TAG: xxxxx
         TOKEN: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
