name: Run Test Action

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Tests
         id: tag_version
         uses: DFE-Digital/github-actions@GetIntoTeaching/DraftReleaseByTag 
         with:
           TAG: x1
           TOKEN: ${GITHUB_TOKEN} 
       
       - name: Print
         run:  echo ${{steps.tag_version.outputs.release_id}}


