name: Run Test Action

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: Tests
         id: tag_version
         uses: DFE-Digital/github-actions/DraftReleaseByTag@GetIntoTeaching/DraftReleaseByTag 
         with:
           TAG: x1
           TOKEN: secrets.ACTIONS_API_ACCESS_TOKEN
       
       - name: Print
         run:  echo ${{steps.tag_version.outputs.release_id}}


