name: Update Trello

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
        - name: Update Trello
          uses: DFE-Digital/github-actions/AddTrelloComment@Get_into_teaching/Update-trello
          with:
            MESSAGE:      "https://github.com/sfawcett123/Test/blob/master/.github/workflows/test-2.yml"
            CARD:         "THIS IS NOT A VALID CARD"          
            TRELLO-KEY:   ${{ secrets.TRELLO_KEY}}
            TRELLO-TOKEN: ${{ secrets.TRELLO_TOKEN }}
          
          
