name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
       
     - name: Get Release Id from Tag
       id: tag_id
       uses: DFE-Digital/github-actions/DraftReleaseByTag@master
       with:
         TAG: xxxxx
         TOKEN: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
         
     - name: Slack Release Notification
       if: steps.tag_id.outputs.release_id
       uses: rtCamp/action-slack-notify@master
       env:
          SLACK_TITLE: "Mulit line Test"
          SLACK_MESSAGE: |
                         "${{steps.tag_id.outputs.release_body}}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
