name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
       
     - name: Copt
       uses: DFE-Digital/github-actions/CopyPRtoRelease@CopyPRtoRelease/create
       with:
         PR_NUMBER: 10
         RELEASE_ID: 35157528
         TOKEN: ${{secrets.GITHUB_TOKEN}}

