name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
     
     - name: Find Release
       id: tag_id
       uses: DFE-Digital/github-actions/DraftReleaseByTag@sfawcett123-patch-1
       with:
           TAG:   xxxxx
           TOKEN: ${secrets.ACTIONS_API_ACCESS_TOKEN}        
            
     - name: Slack Release Notification
       uses: rtCamp/action-slack-notify@master
       env:
          SLACK_TITLE:   Multi line Test
          SLACK_MESSAGE: ${{ fromJson( steps.tag_id.outputs.release_body) }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
