name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
    
     - name: Chicken
       run:  exit(1)
     
     - name: Dump steps context
       if: always()
       env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
       run: echo "$STEPS_CONTEXT"       
          
          
