name: Run Test Action

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         run: |
             FILE='.github/common_environment.yml'
             yq --help
             sed -e 's/:[^:\/\/]/="/g;s/$/"/g;s/ *=/=/g' ${FILE} | sed -e >> $GITHUB_ENV
                    
       - name: Print
         if:  steps.tag_fail.outputs.release_id
         run:  |
               echo URL = ${{env.SLACK_ICON}}
               echo APPLICATION = ${{env.APPLICATION}}           
               


