name: Update Release

on:
  workflow_dispatch:

env:
  PR_NUMBER: 10
  RELEASE_ID: 35157528
  TOKEN:   ${{secrets.GITHUB_TOKEN}}
      
jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:

       - name: Copy PR to Release
         run: |
              BODY=$(curl -s -X GET -H "Authorization: token ${{env.TOKEN}}" "https://api.github.com/repos/${{github.repository}}/pulls/${{env.PR_NUMBER}}" | jq -r ".body" )
              echo "{ 'body' :| '${BODY}' } " > tempfile 
              curl -0 -X PATCH -H "Authorization: token ${{env.TOKEN}}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository}}/releases/${{env.RELEASE_ID}} --data-binary @tempfile
               


