name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
     
     - name: Find Release
       id: release
       run: |
           JSON=$( curl -s -X GET "https://api.github.com/repos/sfawcett123/Test/releases" |  jq '.[] | select( .tag_name=="xxxxx" )' )
           NUM=$( echo ${JSON} | tr '\r\n' ' ' | jq '.id')
           if [[ -z ${NUM} ]] ;
           then
              echo "xxxxx not found"
              echo ::set-output name=release_id::""
           else
              echo "xxxxx found id is ${NUM}"
              echo "::set-output name=release_body::$( echo ${JSON} | tr '\r\n' ' ' | jq -r '.body')"
              echo ::set-output name=release_name::$( echo ${JSON} | tr '\r\n' ' ' | jq -r '.name')
              echo ::set-output name=release_sha::$(  echo ${JSON} | tr '\r\n' ' ' | jq -r '.target_commitish' )
              echo ::set-output name=release_id::"${NUM}"
           fi
    
            
     - name: Slack Release Notification
       uses: rtCamp/action-slack-notify@master
       env:
          SLACK_TITLE: "Mulit line Test"
          SLACK_MESSAGE: ${{ steps.release.outputs.release_body }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
