name: Run Test Action

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         uses: DFE-Digital/github-actions/set-up-environment@setup-environment-ruby        
                         
       - name: Print
         run:  |
               echo URL                  = ${{env.SLACK_ICON}}
               echo APPLICATION          = ${{env.APPLICATION}}     
               echo DOCKERHUB_REPOSITORY = ${{env.DOCKERHUB_REPOSITORY}}
               echo DOMAIN               = ${{env.DOMAIN}}
               echo PAAS_APPLICATION_NAME= ${{env.PAAS_APPLICATION_NAME}}
               echo SLACK_FAILURE        = "${{env.SLACK_FAILURE}}"
               echo SLACK_SUCCESS        = "${{env.SLACK_SUCCESS}}"    
               


