name: Update Release

on:
  workflow_dispatch:

jobs:
  update-release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@main
     
     - name: Find Release
       id: release
       shell: pwsh
       run: |
            $json = $JSON=Invoke-RestMethod -Uri “https://api.github.com/repos/sfawcett123/Test/releases”
            $myTag = $json.Where{ $_.tag_name -eq 'xxxxx' }
            if ( !$myTag.id )
            {
                echo "xxxxxx Tag Not Found"
                echo ::set-output name=release_body::""
            }
            else
            {
                $body=$myTag.body
                echo $myTag.id
                echo "::set-output name=release_body::$(@{body=$body}| ConvertTo-Json -Compress)"
            }
    
            
     - name: Slack Release Notification
       uses: rtCamp/action-slack-notify@master
       env:
          SLACK_TITLE: "Mulit line Test"
          SLACK_MESSAGE: ${{ fromJson( steps.release.outputs.release_body) }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
