name: Run Test Action

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Deployment
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: Tests
         id: tag_version
         uses: DFE-Digital/github-actions/DraftReleaseByTag@getintoteaching/release_details 
         with:
           TAG: x1
           TOKEN: ${{secrets.ACTIONS_API_ACCESS_TOKEN}}
       
       - name: Print
         run:  |
               echo ID ${{steps.tag_version.outputs.release_id}}
               echo NAME ${{steps.tag_version.outputs.release_name}}
               echo BODY ${{steps.tag_version.outputs.release_body}}


