  
name: Read Trello

on:
  pull_request:
    types: [ opened , synchronize ]
  push:
    branches:
      - master
  
jobs:
  read_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Print Message
        run: echo ${{github.event.message}}
